--- 
abstract: Catalyst Model Over Data::Localize
author: 
  - Daisuke Maki C<< <daisuke@endeworks.jp> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Model-Data-Localize
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Runtime: 0
  Class::C3::Adopt::NEXT: 0
  Data::Localize: 0
version: 0.00005
