---
abstract: 'Catalyst Model Over Data::Localize'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-Data-Localize
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Runtime: 0
  Data::Localize: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00003
